# -*- coding: utf-8 -*-
"""Unmount Google Drive from Colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SUMPN66706NujoE9s1uhbpEjI6UEfzb3
"""

import subprocess

## Using Python
subprocess.run(["fusermount", "-u", "/content/drive_sa"], check=False)
subprocess.run(["umount", "/content/drive_sa"], check=False)

